- ssm_jax/hmm/models.py
Fix reshaping of `emissions` so that broadcasting works with `HMM.emission_distribution.log_prob()` works for both scalar and vector observations.
The behaviour is now:
- **scalar** - (T,) --[reshape]--> (T,1)  --[tfp broadcast]--> (T,K).
- **vector** - (T,D) --[reshape]--> (T,1,D) --[tfp broadcast]--> (T,K).
This fixes many methods in HMM subclasses with scalar observations (e.g. `CategoricalHMM.filter()`, `CategoricalHMM.smoother()`, etc.).
The PR also changes a line in `BaseHMM.log_prob()` to only sum over the leading axis, this helps for a failure case whereby extra dimensions in the input can cause broadcasting of the tfp log prob which is subsequently hidden by a `.sum()`.
With the present change the method will output an array with shape determined by the broadcasting (e.g. if `x` …
> Fix broadcasting in calculating emission log probs

- ssm_jax/lgssm/demos/kf_parallel.py
- ssm_jax/lgssm/demos/kf_spiral.py
- ssm_jax/lgssm/demos/kf_tracking.py
- ssm_jax/lgssm/inference.py
- ssm_jax/lgssm/inference_test.py
- ssm_jax/lgssm/models.py
- ssm_jax/misc/plot_utils.py
The function `lgssm.inference.lgssm_filter` is updated to return as `LGSSMPosterior` object to match the behaviour of `lgssm.inference.lgssm_smoother`. 
The `LGSSMPosterior` dataclass is updated so that it can be instantiated without values from the smoothing posterior. 
Instances of the use of the filtering function have been updated to work with the new output.
There are also some changes to the docstrings in `lgssm/inference.py` to be more informative and to standardise formatting a bit.
---
The test in `lgssm/inference_test.py` is updated to use a more rigorous dynamical system and to remove unnecessary additional calls to `lgssm_filter` which is called in `LinearGaussianSSM.smoother()`.
---
The `kf_tracking.py` demo is updated, and the `kf_spiral.py` and `kf_parallel.py` demos are …
> Update lgssm filtering output and port lgssm demos from JSL.

- ssm_jax/hmm/inference.py
- ssm_jax/hmm/inference_test.py
Fix bugs in `hmm_posterior_sample` and verify correctness using unit test created as `test_hmm_posterior_sample`.
Since `hmm_posterior_sample` returns a random output, there seemed to be no straightforward way to implement its unit test. 
Initially, I considered computing the probabilities of each of the possible state sequences, running `hmm_posterior_sample` many times and comparing the sampled frequencies across the possible sequences with the theoretical probabilities.
This seemed needlessly complicated, and the frequencies tended not to uniformly converge to the theoretical values when performing a reasonable number of random samples.
In the end, I settled on the approach of computing the mode sequence of the generated random samples and comparing it to the posterior mode computed by …
> Reimplement hmm_posterior_sample

- ssm_jax/lgssm/demos/demos_test.py
- ssm_jax/lgssm/demos/kf_linreg.py
Convert the `linreg_kf.py` demo to ssm-jax.
Aside from making it run using the ssm-jax `lgssm_filter`, the conversion included some small, mostly cosmetic, changes to the code, updated docstrings, and separated out the plotting code to enable it to run in test mode.
The demo has been added to the list of tests in `lgssm/demos/demos_test.py`.
> Add online linear regression demo from JSL.

- ssm_jax/hmm/inference_test.py
Reimplement `test_hmm_posterior_sample`, the unit test for `hmm_posterior_sample`.
As suggested by @murphyk's [comment](https://github.com/probml/ssm-jax/pull/26#issuecomment-1142354276), I reimplemented the unit test for `hmm_posterior_sample` to do the following:
1. Take `num_samples=1000000` random samples from `hmm_posterior_sample` and compute the relative frequencies of each possible state sequence.
2. Compute theoretical complete joint probabilities using `big_log_joint`.
3. Compare the two distributions to absolute tolerance `eps=1e-3`.
4. Iterate with `num_iterations=5` different random seeds.
With a sample size of 1 million per iteration, the sampled distribution matched the theoretical one to `1e-3` (0.1%) tolerance.
#8
> Reimplement test_hmm_posterior_sample to compare with full joint probs

- ssm_jax/hmm/demos/fixed_lag_smoother.ipynb
- ssm_jax/hmm/inference.py
- ssm_jax/hmm/inference_test.py
- Reimplement [`fixed_lag_smoother`](https://github.com/probml/JSL/blob/main/jsl/hmm/hmm_lib.py#L378) as `hmm_fixed_lag_smoother` in [inference.py](https://github.com/probml/ssm-jax/blob/main/ssm_jax/hmm/inference.py).
- Add unit test as `test_hmm_fixed_lag_smoother` in [inference_test](https://github.com/probml/ssm-jax/blob/main/ssm_jax/hmm/inference_test.py)
- Add Jupyter demo that compares performance of iterative vs vectorized versions as `fixed_lag_smoother.ipynb` and add to [smm_jax/hmm/demos](https://github.com/probml/ssm-jax/blob/main/ssm_jax/hmm/demos)
- For consistency with the rest of the API, `hmm_fixed_lag_smoother` naively assumes that we have the complete observations for all timesteps in the form of `log_likelihoods` available (i.e., off-line, rather than on-line …
> Reimplement hmm_fixed_lag_smoother

- ssm_jax/lgssm/info_inference.py
- ssm_jax/lgssm/info_inference_test.py
`ssm_jax/lgssm/info_inference.py` contains code for kalman filtering in information form.
The implementation more-or-less mirrors the filtering in `lgssm.inference` with `_predict()` and `_condition_on()` changed to accept and return precision (`Lambda`) and precision-weighted mean (`eta`).
`ssm_jax/lgssm_info_inference.py` contains tests which compare the output of `lgssm.info_inference.lgssm_info_filter` to `lgssm.inference.lgssm_filter`. There are currently two tests:
- `test_info_kalman_filter` - simple test with stationary system.
-  `test_info_kf_linreg` - uses the example in `lgssm/demos/kf_linreg.py` to test non-stationary parameters.
> Add information form filtering.

- ssm_jax/lgssm/info_inference.py
- ssm_jax/lgssm/info_inference_test.py
- ssm_jax/lgssm/models.py
- Add the log likelihood calculation to `lgssm_info_filter`.
- Add assertion to info-moment comparison test.
- Add `lgssm_info_smoother` which does information form smoothing. 
- Convert the filtering test to now compare both filter and smoother outputs between information and moment form.
This resolves #11.
There are a couple of potential optimisations that could be made to the smoothing code: 
- **Numerical stability** - convert to a more stable form to ensure symmetry, analogous to the following in the info filter:
```python
ImKF = I - K @ F.T
Lambda_pred = ImKF @ Q_prec @ ImKF.T + K @ Lambda @ K.T
```
- **Avoid duplicate marginalisation**:
- At present the `_smooth_step` function recalculates the predicted parameters $\eta_{t+1|t}, \Lambda_{t+1|t}$ from the filter.
- As in information …
> Kalman info form marginal log likelihood and smoothing

- README.md
> add black installation command to readme

- ssm_jax/abstractions.py
- ssm_jax/distributions.py
- ssm_jax/distributions_test.py
- ssm_jax/hmm/models/base.py
- ssm_jax/hmm/models/bernoulli_hmm.py
- ssm_jax/hmm/models/categorical_hmm.py
- ssm_jax/hmm/models/gaussian_hmm.py
- ssm_jax/hmm/models/multinomial_hmm.py
- ssm_jax/hmm/models/poisson_hmm.py
- ssm_jax/hmm/models/tests/gaussian_hmm_test.py
- ssm_jax/hmm/models/tests/learning_test.py
> Adding priors to HMM models

- ssm_jax/hmm/learning_test.py
- ssm_jax/hmm/models/gaussian_hmm.py
(Same as earlier PR #116 , but the changes have been moved to a different branch on the fork)
This pull request results in more numerically stable calculations of Gaussian HMM Sufficient Statistics
- Returns normalized versions of expected sufficient statistics (see math below)
- Catches DBZ errors (which manifest as NaNs) resulting from states with zero probability (`sum_w` contains a 0)
**Drawbacks**
The m-step code is more opaque, due to the weighted average of the batched and normalized and sufficient statistics that must be taken. Previously, when the sufficient statistics were unnormalized, all the parameters in the sufficient statistics could be summed with a `tree_map` call. Now, the initial state and transitition probabilities are summed across batched, but the (normalized) …
> compute normalized gaussian hmm sufficient stats

- ssm_jax/bp/gauss_bp.py
- ssm_jax/bp/gauss_bp_test.py
- ssm_jax/bp/gauss_bp_utils.py
- ssm_jax/bp/gauss_bp_utils_test.py
- ssm_jax/bp/gauss_chain.py
- ssm_jax/bp/gauss_chain_test.py
- ssm_jax/linear_gaussian_ssm/info_inference_test.py
This PR contains a starting point for gaussian belief propagation and a working implementation of message passing on a Gaussian chain.
There are two main components to the PR:
These are contained in `bp/gaus_bp.py`.
These consist of the fundamental building blocks used to manipulate/construct canonical potentials:
- `info_condition`
- `info_marginalise`
- `info_multiply`
- `info_divide`
- `potential_from_conditional_linear_gaussian`
which do what they say on the tin. The consistency of `info_condition` and `potential_from_conditional_linear_gaussian` is tested in `gaus_bp_test.py`.
`gaus_bp` also contains some wrapper functions to apply these basic operations to the special case of canonical potentials over a pair of multivariate normal variables `pair_cpot_*`.
Going forward with the more …
> Belief Propagation on a Gaussian Chain

- ssm_jax/bp/gauss_chain_test.py
- ssm_jax/linear_gaussian_ssm/info_inference_test.py
- ssm_jax/linear_gaussian_ssm/models.py
This PR:
1. Includes the Parameter class in LinearGaussianSSM
2. Makes the LinearGaussianSSM to a child class of SSM
3. Add back the MAP estimator (bug fixed, it turns out the problem is that the prior distributions all have degree_of_freedom of 'integer' type, but the posteriors have float degree_of_freedom as the sufficient statistics are float, and they are not compatible. So I fix it by setting the df parameters of the prior distributions to be float as well )
> Include Parameter class to LinearGaussianSSM

- ssm_jax/cond_moments_gaussian_filter/demos/cmgf_multiclass_logreg_demo.ipynb
- Implemented CMGF online multi-class logistic regression demo as `cmgf_logistic_regression_demo.ipynb`.
- Performs more accurate inference than single-pass sgd, near-identical performance to many-pass (`max_iter=100`) sgd
- 3-repeated 10-fold cross validation results:
- 10000 data points, 5 features, 2 classes:
- ``EKF-CMGF estimate average accuracy = 0.869``
- ``one-pass sag estimate average accuracy = 0.849``
- ``many-pass sag estimate average accuracy = 0.869``
- 10000 data points, 5 features, 3 classes:
- ``EKF-CMGF estimate average accuracy = 0.681``
- ``one-pass sag estimate average accuracy = 0.61``
- ``many-pass sag estimate average accuracy = 0.681``
- 10000 data points, 5 features, 4 classes:
- ``EKF-CMGF estimate average accuracy = 0.594``
- ``one-pass sag estimate average …
> Add cmgf_multiclass_logreg_demo.ipynb

- ssm_jax/bp/gauss_factor_graph.py
- ssm_jax/bp/gauss_factor_graph_test.py
This PR contains some simple containers for Gaussian variables and Canonical form Gaussian factors as well as a light-weight wrapper to combine these into a factor graph. The containers and inference functions are currently both stored in `ssm_jax/bp/gauss_factor_graph.py`.
Loopy belief propagation is implemented is a functional manner by whereby the core functions take in a `GaussianFactorGraph` object and a dictionary of factor-to-variable messages and return updated messages. I've tried for a clean separation between the static elements (variable, factors, edges) and the dynamic elements (messages and belief states).
The core loop then looks like:
```python
messages = init_messages(factor_graph)
for _ in range(n_itr):
messages = update_all_messages(factor_graph, messages)
```
aiming …
> Functional Loopy bp in a Gaussian Factor Graph.

- ssm_jax/cond_moments_gaussian_filter/containers.py
- ssm_jax/cond_moments_gaussian_filter/inference.py
- ssm_jax/cond_moments_gaussian_filter/inference_test.py
- ssm_jax/containers.py
- ssm_jax/extended_kalman_filter/demos/ekf_mlp.py
- ssm_jax/extended_kalman_filter/inference.py
- ssm_jax/linear_gaussian_ssm/inference.py
- ssm_jax/linear_gaussian_ssm/inference_test.py
- ssm_jax/nonlinear_gaussian_ssm/containers.py
- ssm_jax/unscented_kalman_filter/inference.py
- Unified `LGSSMPosterior`, `NLGSSMPosterior`, and `CMGFPosterior` to `GSSMPosterior` in `ssm_jax/containers.py`.
- Updated references to the redundant `Posterior` objects.
- Since `CMGFParams` takes `Callable` function as its emission covariance whereas `NLGSSMParams` takes an array, I did not unify those two.
- Updated name `emission_var_function` in `CMGFParams` to `emission_cov_function`.
Issue #204
> Remove redundant Posterior containers

- ssm_jax/cond_moments_gaussian_filter/demos/cmgf_multiclass_logreg_demo.ipynb
- Compared 10-fold cv average accuracy of CMGF-EKF against one-pass and many-pass SGD
- Compared training speed vs dataset size of CMGF-EKF against one-pass and many-pass SGD
- Implemented multinomial logistic regression as $(K-1)$ binary CMGF-EKF regressions and performed the equivalent comparisons.
- Overall, CMGF-EKF performs comparably to many-pass SGD in terms of accuracy, and trains faster than many-pass SGD (though slower than one-pass SGD) given a large enough dataset.
- Switching multinomial logistic regression to $(K-1)$ binary logistic regressions does not seem to help with speed.
#208
> Add accuracy, speed comparison with SGD for CMGF multiclass logistic regression

- ssm_jax/distributions.py
Add the tfp bug fix to the `NormalInverseGamma` class to match other distributions which inherit from `tfd.JointDistributionSequential`.
This resolves 3 tests which were failing under tfp version 0.18:
> ssm_jax/distributions_test.py::test_normal_inverse_gamma_vs_normal_inv_wishart
> ssm_jax/distributions_test.py::test_normal_inverse_gamma_log_prob
> ssm_jax/hmm/models/test_models.py::test_sample_and_fit[GaussianMixtureDiagHMM-kwargs5-covariates5]
> Fix tests failing because of NormalInverseGamma bug

- ssm_jax/distributions.py
- ssm_jax/hmm/models/test_models.py
- ssm_jax/utils.py
As described in #221 this adds an `rtol` argument to `monotonically_increasing` which makes the check slight more permissive:
```python
def monotonically_increasing(x, atol=0, rtol=0):
thresh = atol + rtol*jnp.abs(x[:-1])
return jnp.all(jnp.diff(x) >= -thresh)
```
This resolves the previous failing test on `MultivariateNormalDiagHMM`.
> Add relative tolerance to the monotonically increasing check

- dynamax/linear_gaussian_ssm/parallel_inference.py
- dynamax/linear_gaussian_ssm/parallel_inference_test.py
Following the discussion in #233 this PR fixes the discrepancy between the serial and parallel inference algorithms by removing the initial 'predict step' in the parallel algorithm.
Additionally update and refactor the test to reflect the fact that we now expect these two algorithms to produce the identical  output (to within numerical error).
> Fix the initial step in parallel lgssm inference.

- dynamax/abstractions.py
- dynamax/hmm/models/abstractions.py
- dynamax/hmm/models/autoregressive_hmm.py
- dynamax/hmm/models/bernoulli_hmm.py
- dynamax/hmm/models/categorical_glm_hmm.py
- dynamax/hmm/models/categorical_hmm.py
- dynamax/hmm/models/gaussian_hmm.py
- dynamax/hmm/models/gmm_hmm.py
- dynamax/hmm/models/initial.py
- dynamax/hmm/models/linreg_hmm.py
- dynamax/hmm/models/logistic_regression_hmm.py
- dynamax/hmm/models/multinomial_hmm.py
- dynamax/hmm/models/poisson_hmm.py
- dynamax/hmm/models/test_models.py
- dynamax/hmm/models/transitions.py
- dynamax/linear_gaussian_ssm/inference_test.py
- dynamax/linear_gaussian_ssm/linear_gaussian_ssm.py
- dynamax/linear_gaussian_ssm/linear_gaussian_ssm_conjugate.py
- dynamax/parameters.py
- dynamax/parameters_test.py
This PR changes hmm parameters to be stored in nested dataclasses rather than dictionaries.
This introduces four different types of dataclass, one for initial params, one for transition params, one for emissions params and the top level class which houses an instance of each of the above. Something like:
```python
@chex.dataclass
class InitialParams:
probs: Float[Array, "state_dim"]
@chex.dataclass
class TransitionsParams:
transition_matrix: Float[Array, "state_dim state_dim"]
@chex.dataclass
class EmissionsParams:
means: Float[Array, "state_dim emission_dim"]
scales: Float[Array, "state_dim emission_dim"]
@chex.dataclass
class Params:
initial: InitialParams
transitions: TransitionsParams
emissions: EmissionsParams
```
This PR defines the appropriate dataclasses and updates the relevant …
> Update hmm parameters to use dataclasses instead of dicts.

- dynamax/generalized_gaussian_ssm/inference.py
- dynamax/linear_gaussian_ssm/inference.py
- dynamax/linear_gaussian_ssm/info_inference.py
- dynamax/linear_gaussian_ssm/models.py
- dynamax/linear_gaussian_ssm/parallel_inference.py
- dynamax/nonlinear_gaussian_ssm/inference_ekf.py
- dynamax/nonlinear_gaussian_ssm/inference_ukf.py
- dynamax/utils/distributions.py
- dynamax/utils/utils.py
In cases where the matrix A should be is positive semidefinite, replace jnp.linalg.solve with wrapper in `utils/utils.py` so that we have control over the solver used.
For the time being the solver itself is not changed.
Note that the wrapper is only used is scenarios where I was reasonably confident that the matrix A is psd.
> Add wrapper to linear solve.

- docs/notebooks/hmm/gaussian_hmm.ipynb
- dynamax/hidden_markov_model/inference.py
Closes #290 
- Updates calculation in `hmm_smoother`, `_compute_sum_transition_probs` to handle hard zeroes without cascading NaN values into posterior probabilities
- Updates the [GaussianHMM example in the docs](https://probml.github.io/dynamax/notebooks/hmm/gaussian_hmm.html) to not use a sparse transition matrix, to avoid potential user confusion.
cc @slinderman
> [FIX] Handle zeros in transition matrix, update GaussianHMM example

- dynamax/linear_gaussian_ssm/__init__.py
- dynamax/linear_gaussian_ssm/inference.py
- dynamax/linear_gaussian_ssm/models.py
- dynamax/linear_gaussian_ssm/parallel_inference.py
- dynamax/linear_gaussian_ssm/parallel_inference_test.py
- Passes in time indices and make use of helper functions to get correct parameters for making `linear_gaussian_ssm.parallel_inference._make_associative_*_elements`
- Minor addition: Added sampling code that supports LinearGaussianSSM with time-varying parameters by specifying an optional time index `t` input to the emission and transition distributions. An alternative approach is to have the sampling code handle the time-varying parameters and only pass in `params_t`. This code was added to support the parallel inference test code with time-varying techniques and is not essential.
> Support parallel inference in LGSSM with time-varying dynamics

- docs/api.rst
- dynamax/hidden_markov_model/__init__.py
- dynamax/hidden_markov_model/models/gamma_hmm.py
- dynamax/hidden_markov_model/models/test_models.py
Adding an HMM with gamma emissions. This assumes scalar emissions (instead of a vector of conditionally independent gammas) and uses the default M-step.
> adding gamma HMM with generic M-step

- dynamax/linear_gaussian_ssm/inference.py
- dynamax/nonlinear_gaussian_ssm/inference_ekf.py
- dynamax/utils/utils.py
This PR addresses numerical instability in EKF inference and LGSSM inference (issue https://github.com/probml/dynamax/issues/317) by ensuring the covariance matrices output by `extended_kalman_filter` and `lgssm_filter` are symmetric. In both cases this is done by forcibly symmetrizing the output of `_condition_on`. 
The following EKF and LGSSM inference tests pass:
```
from dynamax.nonlinear_gaussian_ssm.inference_ekf_test import (
test_extended_kalman_filter_linear,
test_extended_kalman_filter_nonlinear,
test_extended_kalman_smoother_linear,
extended_kalman_smoother_nonlinear)
test_extended_kalman_filter_linear()
test_extended_kalman_filter_nonlinear()
test_extended_kalman_smoother_linear()
extended_kalman_smoother_nonlinear()
from dynamax.linear_gaussian_ssm.inference_test import …
```
> Symmetrize LGSSM and EKF filtered covariance

- dynamax/linear_gaussian_ssm/inference.py
- dynamax/utils/utils.py
This PR modifies [`lgssm_posterior_sample`](https://github.com/probml/dynamax/blob/a7777671053a66f092077bb29e1a436f6921577d/dynamax/linear_gaussian_ssm/inference.py#L492) to avoid NaNs caused by numerical instability, as described in issue https://github.com/probml/dynamax/issues/320.
Specifically, the new version of `lgssm_posterior_sample` now pads the diagonal of the covariance matrix before passing it to the MVN sampler. The amount of padding is controlled by an optional `jitter` parameter that is set to 0 by default. The code runs identically unless a user specifies a nonzero value for the jitter.
Note that this PR builds on top of https://github.com/probml/dynamax/pull/319 and should be merged second.
> Robust lgssm posterior sample

- dynamax/linear_gaussian_ssm/__init__.py
- dynamax/linear_gaussian_ssm/parallel_inference.py
- dynamax/linear_gaussian_ssm/parallel_inference_test.py
This PR slightly refactors the LGSSM parallel inference code and adds a few new features. The changes include:
- Using named tuples for the messages (i.e. associative scan elements)
- Minor tweaks to function/variable names 
- Adding a posterior sampler (inspired by @ezhang94's implementation!)
- Adding support for bias terms in the dynamics and emissions (still no support for inputs)
- Adding a preamble to explain indexing of the initial state, as [suggested by](https://github.com/probml/dynamax/issues/322#issuecomment-1559655731) by @gileshd 
The code passes the current tests + a new sampling test (courtesy of @ezhang94)
```
from dynamax.linear_gaussian_ssm.parallel_inference_test import (
TestTimeVaryingParallelLGSSMSmoother,
TestTimeVaryingParallelLGSSMSampler, …
```
> Refactor of LGSSM parallel inference

- dynamax/hidden_markov_model/models/arhmm.py
- dynamax/hidden_markov_model/models/gamma_hmm.py
- dynamax/hidden_markov_model/models/gaussian_hmm.py
- dynamax/hidden_markov_model/models/gmm_hmm.py
- dynamax/hidden_markov_model/models/linreg_hmm.py
- dynamax/hidden_markov_model/models/logreg_hmm.py
The KMeans initialisation used in many models uses the SKLearn implementation.  The SKLearn call is not seeded, breaking the determinism of the JAX code.  I assume at some point you are going to include a JAX implementation of KMeans, but until then, a simple fix is:
```
key, subkey = jr.split(key)  # Create a random seed for SKLearn.
sklearn_key = jr.randint(subkey, shape=(), minval=0, maxval=2147483647)  # Max int32 value.
km = KMeans(self.num_states, random_state=int(sklearn_key)).fit(emissions.reshape(-1, self.emission_dim))
```
The original flaw and solution are demonstrated in [this notebook](https://colab.research.google.com/drive/1G68iCObtt6rV0Eh-BlgSSMc0c-gdE3ed?usp=sharing).
Thanks,
A
> Non-determinism in SKLearn KMeans initialisation

- dynamax/linear_gaussian_ssm/inference.py
- dynamax/linear_gaussian_ssm/inference_test.py
- dynamax/linear_gaussian_ssm/parallel_inference.py
- dynamax/linear_gaussian_ssm/parallel_inference_test.py
This PR addresses issue https://github.com/probml/dynamax/issues/331 by allowing the emissions covariance to be stored as a static or time-varying 1D array containing just the diagonal entries and optimizing certain computations when this is the case. Changes include:
- Modified the type signature for [ParamsLGSSMEmissions](https://github.com/calebweinreb/dynamax/blob/e1d4d02fa160f81e3b4ee4478107e0c3f5cb1c61/dynamax/linear_gaussian_ssm/inference.py#L93)
- Rewrote `_get_params` in [inference.py](https://github.com/calebweinreb/dynamax/blob/e1d4d02fa160f81e3b4ee4478107e0c3f5cb1c61/dynamax/linear_gaussian_ssm/inference.py#L148) and [parallel_inference.py](https://github.com/calebweinreb/dynamax/blob/e1d4d02fa160f81e3b4ee4478107e0c3f5cb1c61/dynamax/linear_gaussian_ssm/parallel_inference.py#L49 …
> LGSSM with diagonal noise

- dynamax/utils/utils.py
More stable version of `psd_solve` that addresses https://github.com/probml/dynamax/issues/334.
- The input matrix is symmetrized
- Only the diagonal is boosted
- Uses `cho_factor` / `cho_solve` instead of `linalg.solve`
> Stable psd solve

- dynamax/generalized_gaussian_ssm/inference.py
- dynamax/hidden_markov_model/inference.py
- dynamax/hidden_markov_model/inference_test.py
- dynamax/hidden_markov_model/models/arhmm.py
- dynamax/linear_gaussian_ssm/inference.py
- dynamax/linear_gaussian_ssm/info_inference.py
- dynamax/nonlinear_gaussian_ssm/inference_ekf.py
- dynamax/nonlinear_gaussian_ssm/inference_ukf.py
Why? Following NumPy's [NEP 52](https://numpy.org/neps/nep-0052-python-api-cleanup.html) API cleanup, `np.row_stack` is being removed, as it is a simple alias of `np.vstack`. JAX is following suit by deprecating `jnp.row_stack` in https://github.com/google/jax/pull/17233. Note that `jnp.vstack` is an identical replacement.
> Replace jnp.row_stack with jnp.vstack

- dynamax/linear_gaussian_ssm/models.py
Talked to @mazzulab about issue with time-varying weights in LGSSM. Found that the sample code needs to pass through to `lgssm_joint_sample` in the inference code since the base SSM object doesn't support time-varying parameters in the sample code. Also dug into issues with fitting LGSSM and made some changes to his notebook to address those problems.
> Addressing issue 347: time varying weights in LGSSM

- dynamax/hidden_markov_model/__init__.py
- dynamax/hidden_markov_model/inference_test.py
- dynamax/hidden_markov_model/parallel_inference.py
This PR implements a parallel version of HMM posterior sampling using associative scan (see https://github.com/probml/dynamax/issues/341). The scan elements $E_{ij}$ are vectors specifying a sample
z_j ~ p(z_j \mid z_i)
for each possible value of $z_i$. They can be thought of as functions $E : [1,...,n] \to [1,...,n]$ where the associative operator is function composition. This implementation passes the test written for serial sampling (which is commented out for some reason). It starts performing better than serial sampling when the sequence length exceeds a few thousand (I'm a little mystified as to why it takes so long for the crossover to happen).
```python
from dynamax.hidden_markov_model.inference_test import random_hmm_args
from dynamax.hidden_markov_model import …
```
> Parallel hmm posterior sample

- dynamax/generalized_gaussian_ssm/inference.py
- dynamax/hidden_markov_model/inference.py
- dynamax/linear_gaussian_ssm/inference.py
- dynamax/linear_gaussian_ssm/info_inference.py
- dynamax/nonlinear_gaussian_ssm/inference_ekf.py
- dynamax/nonlinear_gaussian_ssm/inference_ukf.py
- dynamax/nonlinear_gaussian_ssm/sarkka_lib.py
- setup.cfg
Fixes issue https://github.com/probml/dynamax/issues/364 by using the `reverse=True` keyword argument in `lax.scan` function.
Tests are passing locally except for the unscented kalman filter inference tests, but these were also failing for the original code as far as I can tell?
I also had to pin `numpy < 2.0` because `tensorflow_probability` was failing (note that this is also a problem in the [docs](https://probml.github.io/dynamax/notebooks/hmm/gaussian_hmm.html).
There could potentially be further improvement in eliminating unnecessary memory copies by array slicing but I think it would destroy some of the readability of the code and result in some computation overhead. For example, the stack operations (`jnp.vstack([smoothed_probs, filtered_probs[-1]])` and  slicing …
> Use reverse=True keyword argument in lax.scan for smoothers

- paper/paper.md
This PR corrects a typo in the affiliation field.
This is as part of the repo's JOSS review: https://github.com/openjournals/joss-reviews/issues/7069
> Correct typo

- dynamax/hidden_markov_model/models/test_models.py
This PR changes the parameters of the `LinearRegressionHMM` test to prevent it failing.
At present the `LinearRegressionHMM` `test_sample_and_fit` test is failing. The `monotonically_increasing` assertion is failing as the log likelihoods quickly become `jnp.nan`.
I think this is fundamentally a question of the stability of the linear solve. I have made some changes to the inputs which are hopefully more robust to solving.
Changes:
- Replace `jnp.ones` input with `jr.normal`.
- Reduce size of hidden state to 3.
There are likely more principled ways of choosing a more robust test case but in the interest of getting the test to pass I think it is helpful to make a simple change quickly.
Additional changes:
- Remove unused `datetime` import and commented lines.
> Fix failing LinRegHMM test 

- dynamax/parameters.py
Adds a `__repr__` method to the `ParameterProperties` class that returns a string representation of the object. 
This is a QOL improvement for interacting with `ParameterProperties` objects in an interactive environment.
> Add __repr__ method to ParameterProperties

- dynamax/linear_gaussian_ssm/parallel_inference.py
- dynamax/linear_gaussian_ssm/parallel_inference_test.py
I adapted the equations of the parallel Kalman filter and smoother to deal with inputs as well, which was mentioned in #233.
Please let me know if there are any extra tests I should run.
> Parallel Kalman filter and smoother with inputs

- .github/workflows/run_tests.yml
Add the coverage report to the GH action - report will be printed in the GH action.
Additionally install the `test` dependencies rather than the `dev` dependencies - this should test that our `test` dependencies are sufficient to run the tests.
> Add coverage to test workflow

- .github/workflows/interrogate.yml
- pyproject.toml
- setup.cfg
This PR is a suggestion as part of the JOSS review process. It adds a workflow to test the coverage of objects within Dynamax. You may wish to alter the limits or exclude certain files, but I will leave this decision up to you, should you wish to include this PR.
https://github.com/openjournals/joss-reviews/issues/7069
> Add interrogate workflow

- dynamax/utils/distributions.py
- dynamax/utils/distributions_test.py
This PR aims to address the wrong samples generated by the `dynamax.utils.distributions.InverseWishart` (and by extension, those related to `NormalInverseWishart`, `MatrixNormalInverseWishart`, and `LinearGaussianConjugateSSM`). See issue #407.
**Diagnosis**
The inverse Wishart is related by the Wishart distribution as
$` X^{-1} \sim W(\nu, \psi) \leftrightarrow X \sim W^{-1}(\nu, \psi^{-1}) `$
The original implementation computed the inverse of the Cholesky decomposition $\psi = L L^T$, instead of the Cholesky decomposition of the inverse $\psi^{-1}$.
**Fix**
Swap the order of the operations.
I've adapted the code snippet in #407 to be used as accompanying unit test.
> Bugfix InverseWishart scale matrix

- dynamax/utils/distributions.py
- dynamax/utils/distributions_test.py
This PR corrects the broken `InverseWishart.variance` function (see #409). 
**Diagnosis**
The variance of the inverse Wishart distribution $`\Sigma \sim \mathcal{W}^{-1}(\psi, \nu)`$ is given by
$`
var(\Sigma_{ij}) = \frac{(\nu - p + 1) \psi_{ij}^2+ (\nu - p - 1)\psi_{ii} \psi_{jj}}{(\nu - p)(\nu - p - 1)^2 (\nu - p - 3)} 
`$
The original function incorrectly implemented the $`\psi_{ii} \psi_{jj}`$ term as follows
```python
rows = jnp.arange(dim)[:, None].repeat(3, axis=1)
cols = jnp.arange(dim)[None, :].repeat(3, axis=0)
diag[rows] * diag[cols]
```
which explicitly hardcodes the number `3`.
**Fix**
Use Einstein summation convention to rewrite as a one-liner:
```python
Ψii_Ψjj = jnp.einsum('...ii,...jj->...ij', scales, scales)
```
This has the bonus that it automatically vectorizes over …
> Bugfix InverseWishart variance calculation

- dynamax/utils/optimize.py
- dynamax/utils/test_optimize.py
As described in issue #414, the `run_sgd` function fails to correctly optimize the loss, when the `batch_size` does not equal the entire training dataset.
**Diagnosis**:
Compiled JAX functions do not run Python code. Functions passed to `lax.scan` and `lax.while_loop` are compiled, regardless of whether `jax.jit` is used. The comment in the original code correctly identifies that this might be a problem.
**Solution**:
Prevent relevant Python code from being compiled. Usually, the `value_and_grad(loss_fn)` is the most computationally heavy part of the function. I've put a jit around that function. The Python loops and iterators should have minimal additional overhead compared to the original `jax.lax.scan` and `jax.lax.while_loop`.
> Bugfix `run_sgd` mini batch optimization

- .gitignore
- pyproject.toml
The bug in tensorflow probability (https://github.com/tensorflow/probability/issues/1814) seems to be resolved, so we can relax our numpy version pin finally!
> removing numpy<2.0 pin and ignoring coverage outputs
