probml/dynamax

- .github/workflows/workflow.yml
- .gitignore
- pyproject.toml
- requirements.txt
- setup.py
> Added GitHub workflow

- ssm_jax/hmm/learning.py
- ssm_jax/hmm/learning_test.py
- ssm_jax/hmm/models/base.py
- ssm_jax/hmm/models/bernoulli_hmm.py
- ssm_jax/hmm/models/categorical_hmm.py
- ssm_jax/hmm/models/categorical_logit_hmm.py
- ssm_jax/hmm/models/gaussian_hmm.py
- ssm_jax/hmm/models/multinomial_hmm.py
- ssm_jax/hmm/models/poisson_hmm.py
- ssm_jax/hmm/models/tests/categorical_logit_hmm_test.py
Issues #81 and #83 are wrt standardizing the M-step interface and generalizing the BaseHMM interface for `emission_distribution`, etc.
> Address issues 81 and 83

- ssm_jax/cond_moments_gaussian_filter/containers.py
- ssm_jax/cond_moments_gaussian_filter/inference.py
- ssm_jax/cond_moments_gaussian_filter/inference_test.py
- Implemented CMGF as `conditional_moments_gaussian_filter()` in `cond_moments_gaussian_filter/inference.py`. 
- Implemented ICMGF as `iterated_conditional_moments_gaussian_filter()` in `cond_moments_gaussian_filter/inference.py`. 
- Implemented CMGS as `conditional_moments_gaussian_smoother()` in `cond_moments_gaussian_filter/inference.py`. 
- Implemented ICMGS as `iterated_conditional_moments_gaussian_smoother()` in `cond_moments_gaussian_filter/inference.py`. 
- Tested against naive EKF implementation in `test_ekf()` in `cond_moments_gaussian_filter/inference_test.py`. 
- Tested against naive UKF implementation in `test_ukf()` in `cond_moments_gaussian_filter/inference_test.py`. 
#140
> Implement Conditional Moments Gaussian Filter (CMGF)

- ssm_jax/hmm/demos/gaussian_hmm_2d.py
- ssm_jax/hmm/models/gaussian_hmm.py
> Fix params given to niw_posterior_update in the wrong order

- ssm_jax/kmeans.py
- ssm_jax/kmeans_test.py
> Implement KMeans and KMeans++ algorithms

- ssm_jax/hmm/inference.py
kicking the tyres of github PRs
> add callable params

- ssm_jax/hmm/inference.py
- ssm_jax/hmm/inference_test.py
- ssm_jax/hmm/models/base.py
added transition_fn callables to HMM inference
> added transition_fn callables to HMM inference

- ssm_jax/cond_moments_gaussian_filter/demos/cmgf_logistic_regression.py
- ssm_jax/cond_moments_gaussian_filter/demos/cmgf_mlp_classifier.py
- ssm_jax/cond_moments_gaussian_filter/demos/cmgf_poisson.py
Translated `cmgf_logistic_regression.py`, `cmgf_mlp_classifier.py`, and `cmgf_poisson.py`.
> Translate CMGF Demo Notebooks into Python Files

- ssm_jax/cond_moments_gaussian_filter/demos/cmgf_poisson.py
Added CMGF-GHKF inference to Poisson likelihood demo.
> Add CMGF-GHKF inference to Poisson likelihood demo.

- ssm_jax/linear_gaussian_ssm/models/linear_gaussian_ssm.py
Replace with Nones with zeros in `_make_inference_args` and do not include bias term in distribution calculations.
Resolves #224.
> Handle absence of bias term.

- README.md
- docs/api.rst
- docs/index.rst
- dynamax/utils/utils.py
- dynamax/utils/utils_test.py
- setup.cfg
See `dynamax.utils.utils.find_permutation`
> Add a helper function for finding permutations that align two state sequences

- dynamax/generalized_gaussian_ssm/inference.py
- dynamax/linear_gaussian_ssm/inference.py
- dynamax/linear_gaussian_ssm/info_inference.py
- dynamax/linear_gaussian_ssm/models.py
- dynamax/linear_gaussian_ssm/parallel_inference.py
- dynamax/nonlinear_gaussian_ssm/inference_ekf.py
- dynamax/nonlinear_gaussian_ssm/inference_ukf.py
- dynamax/utils/distributions.py
- dynamax/utils/utils.py
Update the name to better reflect where it is used.
> Rename `linear_solve` to `psd_solve`.

- dynamax/linear_gaussian_ssm/inference.py
> support callable parameters for lgssm

- docs/notebooks/hmm/casino_hmm_learning.ipynb
Apologies on the multiple PRs. Using the web editor and catching them as I notice them
> Fix another minor typo

- dynamax/linear_gaussian_ssm/inference_test.py
Reference #229 
Implemented large MVN and added test comparing to Kalman smoother. 
Feedback welcome!
> implement explicit MVN

- docs/notebooks/linear_gaussian_ssm/kf_linreg.ipynb
> fix a typo

- README.md
- docs/index.rst
Update the pdf links to the second edition book
> update links to the second edition of Bayesian Filtering and Smoothing

- dynamax/nonlinear_gaussian_ssm/sarkka_lib.py
Solves issue #367.
Sorry, it turns out I did introduce the error in my PR.
> Fix concat logic in uks, eks

- docs/notebooks/hmm/casino_hmm_learning.ipynb
> DOC: fix a minor typo

- README.md
While reading the math I found that the joint distribution expression shows correct product indices in the documentation here https://probml.github.io/dynamax/
> Update README.md to match equation.
